archive/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include("hello.urls")),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    path('inventory/', include("inventory.urls")),
    ]

equipment/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom django.conf import settingsfrom django.conf.urls.static import staticfrom . import viewsfrom django.contrib.auth.decorators import login_required, permission_requiredfrom equipment.views import (    EquipmentView,    ModelView)app_name = "equipment"urlpatterns =[    path('', login_required(EquipmentView.as_view(template_name="index.html")), name='equipment'),    path('model/<slug:model_id>', login_required(views.loadmodel), name='model'),    path('newmodel', login_required(views.newmodel), name='newmodel'),    path('model', login_required(views.savemodel), name='savemodel'),    path('images', login_required(views.showimage), name='showimage'),        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)        

inventory/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom inventory.views import (    InventoryView,    SearchView)app_name = "inventory"urlpatterns =[	path('', login_required(InventoryView.as_view(template_name="index.html")), name='inven'),	url(r'^$', SearchView.as_view(), name='search'),	path("update_inv", views.update_inv, name ="update_inv"),	path("save_event", views.save_event, name ="save_event"),	path("items", views.items, name ="items"),	path("item", views.item, name ="item"),	path("report", views.report, name ="report"),	path("inv_report", views.inv_report, name ="inv_report"),	path("upload_file", views.upload_file, name ="upload_file"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

locations/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom locations.views import (    LocationView)app_name = "locations"urlpatterns =[    path('', login_required(LocationView.as_view(template_name="index.html")), name='location'),    path("site/<slug:location_id>/", views.site, name ="site"),    path("searchsite", views.searchsite, name ="searchsite"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

tcli/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^users/',include('users.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #url(r'^inventory/',include('inventory.urls')),
    #path('/inventory', search_view),
    path('inventory/', include("inventory.urls"),name='inven'),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

equipment/models.py
from django.db import models
from django.core.files.base import ContentFile
from django.utils import timezone
from django.conf import settings
# info on remote/local storage
#https://docs.djangoproject.com/en/dev/topics/files/



# Create your models here.
class Model(models.Model):  
    timestamp = timezone.now 
    id = models.AutoField(primary_key=True)
    description = models.CharField("description",max_length=100,null=False,unique=False,default='N/A')  
    category  = models.CharField("category",max_length=50,null=False,unique=False,default='N/A')  # Modem, Switch, Modem Switch, Controller, SC-90 Upgrades
    band = models.CharField("band",max_length=50,null=False,unique=False,default='N/A')  # L-Band, Ku-Band, C-Band, Ka-Band
    vendor = models.CharField("vendor",max_length=50,null=True,unique=False)  
    model = models.CharField("Model",max_length=50,null=False,unique=False)  
    comments = models.CharField("comments",max_length=200,null=True,unique=False)  
    image_file = models.CharField("Image_file",max_length=20,null=True,unique=False) 
    status = models.CharField("status",max_length=50,null=True,unique=False) 
    last_update = models.DateField(default=timestamp)
    inventory_id = models.IntegerField(null=True,unique=False)
    photo= models.ImageField(upload_to='media/', blank=True)
        
    def __str__(self):
        return self.description
        
    def get_absolute_url(self):
        return reverse('model', kwargs={'slug': self.id})
		
       
    
	
    def add_new(self, description, category,band, vendor, model, comments, image_file, status, last_update):
        self.description = description
        self.category = category
        self.band = band
        self.vendor = vendor
        self.model = model
        self.comments = comments
        self.image_file = image_file
        self.status = status
        self.last_update = last_update
        self.save()	
		
    def serialize(self):
        return {
            'id': self.id, 
            'description': self.description,
            'category': self.category,
            'band': self.band,
            'vendor': self.vendor,
            'model': self.model,
            'comments': self.comments,
            'image_file': self.image_file,
            'status': self.status,
            'last_update': self.last_update,
            'inventory_id': self.inventory_id,
        }  

templates/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

def __str__(self):
    return self.user.username

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

def __str__(self):
    return self.user.username

equipment/forms.py
#https://www.pluralsight.com/guides/work-with-ajax-django

from .models import Model
from django import forms
import datetime

class ModelsForm(forms.ModelForm):
    class Meta:
        model= Model
        fields= ["photo", "model"]

class EquipmentForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(EquipmentForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Model
        fields = '__all__'
        

equipment/views.py
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.core import serializers
from .forms import EquipmentForm, ModelsForm
from datetime import date
from django.urls import reverse,  reverse_lazy
from django.urls import reverse
from django.views import View
from equipment.models import Model
from datetime import date, datetime
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
import datetime
model_id = 0

class EquipmentView(View):
    form_class = EquipmentForm
    template_name = "index.html"
    success_url = reverse_lazy('equipment:equipment')
    contSuccess = 0
    
    def get(self, *args, **kwargs):
        form = self.form_class()
        try:
            models = Model.objects.all()
        except IOError as e:
            print ("Lists load Failure ", e)
            print('error = ',e) 
        return render (self.request,"equipment/index.html",{"form": form, "models": models, "index_type":"EQUIPMENT"})
	   	
    def post(self, request, *args, **kwargs):
        form = self.form_class()
        search = request.POST.get('search', -1)
        print('search =',search)
        success = True
        if not search ==-1:
            models = Model.objects.filter(description__icontains=search) | Model.objects.filter(category__icontains=search) | Model.objects.filter(band__icontains=search) | Model.objects.filter(vendor__icontains=search) | Model.objects.filter(model__icontains=search) | Model.objects.filter(status__contains=search).all()
            if not models:
                models = Model.objects.all()
        else:
            models = Model.objects.all()
        return render (self.request,"equipment/index.html",{"form": form, "models": models, "index_type":"EQUIPMENT"})

class ModelView(View):
    form_class = ModelsForm
    template_name = "model.html"
    success_url = reverse_lazy('equipment:model')
   
    slug = None
    def get_object(self, queryset=None):
        self.slug = self.kwargs.get('slug', None)
        print('slug = ',self.slug)
        mod= []
        models= []
        
    def get(self, *args, **kwargs):
        form = self.form_class()
        try:
            models = Model.objects.all()
            mod = Model.objects.filter(id=self.slug).all()
            print(models)
            print(mod)
        except IOError as e:
            print ("Lists load Failure ", e)
            print('error = ',e) 
        return render (self.request,"equipment/index.html",{"form": form, "models": models, "model": mod,  "index_type":"EQUIPMENT"})
        
    def post(self, *args, **kwargs):
        timestamp = date.today()
        band = request.POST.POST('_band',-1)
        category = request.POST.get('_category',-1)
        description = request.POST.get('_desc',-1)
        model = request.POSTget('_model',-1)
        vendor= request.POST.get('_vendor',-1)
        active = True
        image_file = request.POST.get('fileupload',-1)
        comments = request.POST.get('_comments',-1)
        model_id = request.POST.get('m_id',-1)
        save = request.POST.get('_save',-1)
        update = request.POST.get('_update',-1)
        delete = request.POST.get('_delete',-1)
        
        if not save==None:	
            try:		
                Model.objects.create(description=description, category=category, band=band, vendor=vendor, model=model, 
                        comments=comments, image_file=image_file, status=active, last_update=timestamp)
            except IOError as e:
                success = False
                print ("Models Save Failure ", e)
        elif not update==None: 
            try:
                #update existing event
                Model.objects.filter(id=model_id).update({'description': description,'category':category,'band=':band,
                    'model':model,'comment':comment,'locationname':locationname,'image_file':image_file,'vendor':vendor,'active':active,'last_update':last_update})
            except IOError as e:
                print ("Models Update Failure ", e)	
        elif not delete==None: 
            try:
                Model.objects.filter(id=model_id).delete()
            except IOError as e:
                print ("Models Delete Failure ", e)		
        return render (self.request,"equipment/index.html",{"form": form, "models": models, "index_type":"EQUIPMENT"})

def loadmodel(request, model_id):
        models = []
        mod = []
        print('we are here')
        # cast the request inventory_id from string to integer type.
        model_id = int(model_id)
        success = True 
        try:	
            models=Model.objects.all()
            mod=Model.objects.filter(id=model_id)
            mod=mod[0]
            print('mod.image_file',mod.image_file)
            uploaded_file_url=mod.photo
            if uploaded_file_url==None or uploaded_file_url =="":
                uploaded_file_url = '/tcli/media/inv1.jpg'
            print('uploaded_file_url =',uploaded_file_url)
        except IOError as e:
            print ("load model Failure ", e)
            print('error = ',e) 
        return render(request,"equipment/model.html",{"models": models, "mod": mod, "uploaded_file_url":uploaded_file_url,  "index_type":"Model"})
        
def newmodel(request):
        models = []
        success = True 
        try:	
            mod = -1
            models=Model.objects.all()
            image_file = 'inv1.jpg'
            uploaded_file_url = '/tcli/media/inv1.jpg'
                       
        except IOError as e:
            print ("load model Failure ", e)
            print('error = ',e) 
        return render(request,"equipment/model.html",{"models": models, "mod": mod, "uploaded_file_url":uploaded_file_url, "image_file":image_file,  "index_type":"Model"})

@login_required
def showimage(request):
    image_file = -1
    if request.method == 'POST': 
        form = ModelsForm(request.POST, request.FILES)
        print('form =',form)
        model_id=308
        print('model_id =',model_id)       
        instance = Model.objects.get(id=model_id)
        print('instance =',instance) 
        form = ModelsForm(request.POST or None, instance=instance)
            
        #print('imagefile =',imagefile)
        media_folder = settings.MEDIA_URL
        print('media_folder = ',media_folder)
        #file_path = media_folder+image_file
        #image_file = media_folder + imagefile
        
        #os.rename(file_path,image_file)
       
        if form.is_valid(): 
            form.save() 
    else: 
        form = ModelsForm()
        imagefile = request.POST.get('photo',-1)
        #print('imagefile =',imagefile)
    return render(request, 'equipment/images.html', {'form' : form}) 
   
def loadEquipment():
    import csv
    contSuccess = 0
    CSV_PATH = 'models.csv'
    print('csv = ',CSV_PATH)
    
    # Remove all data from Table
    Model.objects.all().delete()

    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)
    for description, category, band, vendor, model, comments, image_file, status, last_update in reader:
        print(description)
        print (band)
        print(vendor)
        print(model)
        print(comments)
        print(image_file)
        print(status)
        print(last_update)
        Model.objects.create(description=description, category=category, band=band, vendor=vendor, model=model, comments=comments, image_file=image_file, status=status, last_update=datetime.datetime.strptime(last_update, '%m/%d/%Y'))
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ')
 

@login_required
def savemodel(request):
    if request.method == 'POST':
        model_id = request.POST.get('m_id',-1)
        models = Model.objects.all()
        print('model_id=',model_id)
        mod = Model.objects.filter(id__contains=model_id)
        mod=mod[0]
        print('mod=',mod)
        try:        
            image_file = request.FILES.get('_upload',-1)
        except IOError as e:
             image_file = -1
        print('image_file=',image_file)  
        if image_file==-1 or image_file=='inv1.jpg' or image_file== None or image_file== "":
            image_file = mod.image_file
            print(image_file)
            uploaded_file_url = mod.photo
            print('uploaded_file_url =',uploaded_file_url )
        else:    
            myfile = request.FILES['_upload']
            print('MYFILE =', myfile)
            fs = FileSystemStorage()
            print('fs=',fs)
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            print('uploaded_file_url =',uploaded_file_url )
            print(image_file)
            
        if uploaded_file_url == None or uploaded_file_url =="":
            uploaded_file_url='/tcli/media/inv1.jpg' 
            image_file='inv1.jpg'
        
        timestamp = date.today()
        band = request.POST.get('_band',-1)
        category = request.POST.get('_category',-1)
        description = request.POST.get('_desc',-1)
        model = request.POST.get('_model',-1)
        vendor= request.POST.get('_vendor',-1)
        active = True
        comments = request.POST.get('_com',-1)
        if comments==-1:
            comments=""
        print('comments=',comments)
        save = request.POST.get('_save',-1)
        update = request.POST.get('_update',-1)
        delete = request.POST.get('_delete',-1)
        
                      
        if not save==-1:	
            try:		
                Model.objects.create(description=description, category=category, band=band, vendor=vendor, model=model, comments=comments, 
                            image_file=image_file, photo=uploaded_file_url, status=active, last_update=timestamp)

equipment/templates/equipment/model.html
{% extends "equipment/layout.html" %}
{% load static %}

{% block title %}
    {{ index_type }}
{% endblock %}

{% block body %}
<body>
   <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
		<a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">TCLI Inventory Manager</a>
		<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
		<ul class="navbar-nav px-3">
		  <li class="nav-item text-nowrap">
			<a class="nav-link" href="{% url 'logout' %}">Sign out</a>
		  </li>
		</ul>
    </nav>
	<div class="container-fluid">
	  <div class="row">
		<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
		  <div class="sidebar-sticky pt-3">
			<ul class="nav flex-column">
			     <li class="nav-item">
					<a class="nav-link active" href="{% url 'index' %}">
					  <span data-feather="home"></span>
					  Home <span class="sr-only">(current)</span>
					</a>
			    </li>
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'inventory:inven' %}">
					  <span data-feather="home"></span>
					  Search Inventory <span class="sr-only">(current)</span>
					</a>
			    </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'inventory:items' %}">
					  <span data-feather="file"></span>
					  Create Inventory items
					</a>
				  </li>
				  {% if mod == -1 %}
						<li class="nav-item">
						<a class="nav-link" href="{% url 'equipment:showimage' %}">
						  <span data-feather="file"></span>
						  Add Image
						</a>
					  </li>
					  <li class="nav-item">
						<a class="nav-link" href="{% url 'equipment:equipment' %}">
						  <span data-feather="file"></span>
						  Search Equipment
						</a>
					  </li>
				  {% else %}
					  <li class="nav-item">
						<a class="nav-link" href="{% url 'equipment:newmodel' %}">
						  <span data-feather="file"></span>
						  Create new Model 
						</a>
					  </li>
				  {% endif %}
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'locations:location' %}">
					  <span data-feather="users"></span>
					  Add Site locations
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">
					  <span data-feather="layers"></span>
					  Log out
					</a>
				 </li>
			 </ul>
		</div>
	</nav>
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
	    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			{% if mod == -1 %}
				<h1 class="h2">Create new Equipment Item</h1>
			{% else %}
			<h1 class="h2">Modify Equipment Item</h1>
				{% endif %}
			<div class="btn-toolbar mb-2 mb-md-0">
				<div class="btn-group mr-2">
					<button type="button" id = "share" class="btn btn-sm btn-outline-secondary">Share</button>
					<button type="button" id = "export" class="btn btn-sm btn-outline-secondary">Export</button>
				</div>
			</div>
		</div>
		<form action = "{% url 'equipment:savemodel' %}"  method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input type='hidden' id = 'm_id' name='m_id' value = {{mod.id}} data-select='inventory_id'/>
			<input type='hidden' id = 'model' name='model' value = {{mod.model}} data-select='model'/>
            <div class="row">
				<div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label>Band <span class="k-required"></span></label>
						<input type='hidden' name='models' data-select='_band'/>
						<select id='_band' name = "_band" value = "{{mod.band}}" class="browser-default custom-select custom-select-lg mb-3" >
							{% if mod == -1 %}
								<option selected>select option</option>
							{% else %}
								<option selected>{{mod.band}}</option>
							{% endif %}
							<option data-desc = 'band', data-val = "n-a">N/A</option>
							<option data-desc = 'band', data-val = "l-band">L-Band</option>
							<option data-desc = 'band', data-val = "C-band">C-Band</option>
							<option data-desc = 'band', data-val = "x-band">X-Band</option>
							<option data-desc = 'band', data-val = "ku-band">Ku-Band</option>
							<option data-desc = 'band', data-val = "ka-band">Ka-Band</option>
						</select>
					</div>
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					 <div class="form-group">
						<label>Category<span class="k-required"></span></label>
						<input type='hidden' name='category' data-select='category'/>
						<select id='_category' name = "_category" value = "{{mod.category}}" class="browser-default custom-select custom-select-lg mb-3" >
							{% if mod == -1 %}
								<option selected>select option</option>
							{% else %}
								<option selected>{{mod.category}}</option>
							{% endif %}
							<option data-desc = 'equipment', data-val = "modem">MODEM</option>
							<option data-desc = 'equipment', data-val = "buc">BUC</option>
							<option data-desc = 'equipment', data-val = "bdc">BDC</option>
							<option data-desc = 'equipment', data-val = "lna">LNA</option>
							<option data-desc = 'equipment', data-val = "lnb">LNB</option>
							<option data-desc = 'equipment', data-val = "amp">AMPLFIER</option>
							<option data-desc = 'equipment', data-val = "ant">ANTENNA</option>
							<option data-desc = 'equipment', data-val = "contr">CONTROLLER</option>
							<option data-desc = 'equipment', data-val = "pcb">PCBOARD</option>
						</select>
					</div>	
				</div>	
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg-4 grid-col">
					<div class="form-group">
						<label for="_desc">Description</label>
						{% if mod == -1 %}
							<input id = "_desc" name = "_desc" input class="form-control" placeholder="Enter description"  required >
						{% else %}
							<input id = "_desc" name = "_desc" input class="form-control" value = "{{mod.description}}"  required >
						{% endif %}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label for="_model">Model/Part</label>
						{% if mod == -1 %}
							<input id = "_model"  name = "_model" input class="form-control"  placeholder="Enter Model"  required autofocus>
						{% else %}
							<input id = "_model"  name = "_model" value = "{{mod.model}}" input class="form-control"  required autofocus>
						{% endif %}
					</div>	
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label for="_vendor">Vendor</label>
						{% if mod == -1 %}
							<input id = "_vendor" name = "_vendor" input class="form-control" placeholder="Enter Vendor"  required autofocus>
						{% else %}
							<input id = "_vendor" name = "_vendor" input class="form-control" value = "{{mod.vendor}}" required autofocus>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="row">	
				<div class="col-sm-3 col-lg-4 grid-col">
					<div class="form-group">
						<label>Comments: </label><br>
						{% if mod == -1 %}
							<textarea id="_com" name = "_com" rows="3" cols="68" style="align-content:left"></textarea>
						{% else %}
							<textarea id="_com" name = "_com" rows="3" cols="68" style="align-content:left">{{mod.comments}}</textarea>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="row">	
				<div class="col-sm-3 col-lg-4 grid-col">
					<div class="form-group">
					    <label for="_upload"> Select an Equipment Image</label> 
						<input type="file" name="_upload" id="_upload"> 
						
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2 col-lg-3 grid-col">
					<div class="thumbnail">
					    <img src="{{ uploaded_file_url }}" class="img-responsive" alt="Cinque Terre">
						<div class="caption" >
							{% if mod == -1 %}
								<p id = "_md" name = '_md' >Model:</p>
							{% else %}
								<p id = "_md" name = '_md' >Model: {{mod.model}}</p>
							{% endif %}
							
						</div>
					</div>	
				</div>
			</div>
			<div class="row">
			    {% if mod == -1 %}
					<div class="col-sm-1 col-lg-1 grid-col">
						<div class="form-group">
							<input type="submit" id = "_save" name = "_save" data-search="save"  value="Save Model">
						</div>
					</div>
				{% else %}
					<div class="col-sm-1 col-lg-1 grid-col">
						<div class="form-group">
							<input type="submit" id = "_update" name = "_update" data-update="save"  value="Update Model">
						</div>
					</div>
					<div class="col-sm-1 col-lg-1 grid-col">
						<div class="form-group">
							<input type="submit" id = "_delete" name = "_delete" data-update="save"  value="Delete Model">
						</div>
					</div>
				{% endif %}
			</div>
		</form>
		{% if uploaded_file_url %}
			<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
		{% endif %}
		<h2 class="text-center">Equipment List</h2>
		<div class="table-responsive" Method = "POST">
			 <table id = "table_id" class="table table-striped table-sm">
			    <thead>
					<tr>
					  <th>ID</th>
					  <th>Description</th>
					  <th>Category</th>
					  <th>Band</th>
					  <th>Model</th>
					  <th>Vendor</th>
					  <th>Status</th>
					</tr>
			    </thead>
				<tbody>
					{% for model in models %}
						<tr>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.id}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.description}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.category}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.band}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.model}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id %}">{{model.vendor}}</td>
							<td><a class="nav-link" href="{% url 'equipment:model' model_id=model.id">{{model.status}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script> 
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>
</body>
{% endblock %}

</html>