archive/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include("hello.urls")),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    path('inventory/', include("inventory.urls")),
    ]

equipment/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom django.conf import settingsfrom django.conf.urls.static import staticfrom . import viewsfrom django.contrib.auth.decorators import login_required, permission_requiredfrom equipment.views import (    EquipmentView,    ModelView)app_name = "equipment"urlpatterns =[    path('', login_required(EquipmentView.as_view(template_name="index.html")), name='equipment'),    path('model/<slug:model_id>', login_required(views.loadmodel), name='model'),    path('newmodel', login_required(views.newmodel), name='newmodel'),    path('model', login_required(views.savemodel), name='savemodel'),    path('images', login_required(views.showimage), name='showimage'),        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)        

inventory/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom inventory.views import (    InventoryView,    SearchView)app_name = "inventory"urlpatterns =[	path('', login_required(InventoryView.as_view(template_name="index.html")), name='inven'),	url(r'^$', SearchView.as_view(), name='search'),	path("update_inv", views.update_inv, name ="update_inv"),	path("save_event", views.save_event, name ="save_event"),	path("items", views.items, name ="items"),	path("item", views.item, name ="item"),	path("report", views.report, name ="report"),	path("inv_report", views.inv_report, name ="inv_report"),	path("upload_file", views.upload_file, name ="upload_file"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

locations/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom locations.views import (    LocationView)app_name = "locations"urlpatterns =[    path('', login_required(LocationView.as_view(template_name="index.html")), name='location'),    path("site/<slug:location_id>/", views.site, name ="site"),    path("searchsite", views.searchsite, name ="searchsite"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

tcli/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^users/',include('users.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #url(r'^inventory/',include('inventory.urls')),
    #path('/inventory', search_view),
    path('inventory/', include("inventory.urls"),name='inven'),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

inventory/forms.py
#https://www.pluralsight.com/guides/work-with-ajax-django

from .models import Inventory
from django import forms
import datetime

class InventoryForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(InventoryForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Inventory
        fields = ("__all__")
        

inventory/views.py
from django import forms
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.core import serializers
from .forms import InventoryForm
from datetime import date
from django.urls import reverse, reverse_lazy
from equipment.models import Model
from locations.models import Location
from inventory.models import Inventory, Events
from django.views import View
import datetime
from django.contrib.auth.decorators import login_required

# Create your views here.
class InventoryView(View):
    '''
    #~~~~~~~~~~~Load Item database from csv. must put this somewhere else later"
    import csv
    timestamp  = date.today()  
    import csv
    timestamp  = date.today()
    CSV_PATH = 'items.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0
    # Remove all data from Table
    #Inventory.objects.all().delete()
    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)

    for category, shelf, modelname, serial_number, description, locationname,  status, remarks,last_update,update_by in reader:
        Inventory.objects.create(category=category, shelf=shelf, modelname=modelname, serial_number=serial_number, description=description, locationname=locationname, 
         status=status, remarks=remarks, last_update=datetime.datetime.strptime(last_update, '%m/%d/%Y'), update_by=update_by)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ') 
    '''
    '''
    #~~~~~~~~~~~Load Events database from csv. must put this somewhere else later"
    import csv
    timestamp  = date.today()      
    CSV_PATH = 'events.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0

    # Remove all data from Table
    Events.objects.all().delete()

    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)
    for event_type, event_date, operator, comment, inventory_id, locationname, rma, rtv, mr, in reader:
        print('event date=',event_date)
        Events.objects.create(event_type=event_type, event_date=datetime.datetime.strptime(event_date, '%m/%d/%Y'), operator=operator,comment=comment, locationname=locationname, mr=mr, rtv =rtv, rma =rma, inventory_id=inventory_id)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ')
    
    #~~~~~~~~~~~Load Events database from csv. must put this somewhere else later"   
    '''
    '''
    import csv
    timestamp  = date.today()
    CSV_PATH = 'locations.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0
    # Remove all data from Table
    Location.objects.all().delete()

    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)
    for name, address, city, state,zip_code, phone, email, website, lat, lng, created_on ,last_entry in reader:
        if lat=="": lat=40.815320
        if lng=="": lng=-73.237710
        Location.objects.create(name=name, address=address, city=city, state=state, zip_code=zip_code, phone=phone, email=email,
                 website=website,active=True, lat=float(lat), lng=float(lng), created_on=timestamp, last_entry=timestamp)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ')
    '''
    #load_iventory_csv(True)
    #load_events_csv(True)
    form_class = InventoryForm
    template_name = "index.html"
    success_url = reverse_lazy('inventory:inv')
    def get(self, *args, **kwargs):
        form = self.form_class()
        try:
            
            description=-1
            category=-1
            model=-1
            status=-1
            locationname=-1
            shelf=-1
            search=-1
            
            print("in GET")
            desc_list = Inventory.objects.order_by('description').values_list('description', flat=True).distinct()
            models_list = Inventory.objects.order_by('modelname').values_list('modelname', flat=True).distinct()
            categorys_list = Inventory.objects.order_by('category').values_list('category', flat=True).distinct()
            status_list = Inventory.objects.order_by('status').values_list('status', flat=True).distinct()
            locations_list = Inventory.objects.order_by('locationname').values_list('locationname', flat=True).distinct()
            shelves_list = Inventory.objects.order_by('shelf').values_list('shelf', flat=True).distinct()
            inv = Inventory.objects.all()
        except IOError as e:
            print ("Lists load Failure ", e)
            print('error = ',e) 
        return render (self.request,"inventory/index.html",{"form": form, "inventory": inv, "desc_list":desc_list, "status_list":status_list,
           "models_list":models_list, "locations_list":locations_list, "shelves_list":shelves_list,"categorys_list":categorys_list, "index_type":"INVENTORY",
           'description':description,'model':model,'status':status, 'category':category, 'locationname':locationname, 'shelf':shelf,'search':search})
    
    def post(self, request, *args, **kwargs):
        try: 
            #print("in POST")
            json_data = []
            inv_list = []
            inv = []
            form = self.form_class()
            #print('request =',request)
            model = request.POST.get('_model', -1)
            #print('model = ',model)
            description = request.POST.get('_desc', -1)
            #print('description = ',description)
            status = request.POST.get('_status', -1)
            #print('status =',status)
            category = request.POST.get('_category', -1)
            #print('category =',category)
            locationname = request.POST.get('_site', -1)
            #print('locationname =',locationname)
            shelf = request.POST.get('_shelf', -1)
            #print('shelf =',shelf)
            select = request.POST.get('sel', -1)
            #print('select =',select)
            search = request.POST.get('search', -1)
            #print('search =',search)
            print_report = request.POST.get('monthly_report', -1)
            #print('print_report =',print_report)
            success = True
            
            

            desc_list = Inventory.objects.order_by('description').values_list('description', flat=True).distinct()
            models_list = Inventory.objects.order_by('modelname').values_list('modelname', flat=True).distinct()
            categorys_list = Inventory.objects.order_by('category').values_list('category', flat=True).distinct()
            status_list = Inventory.objects.order_by('status').values_list('status', flat=True).distinct()
            locations_list = Inventory.objects.order_by('locationname').values_list('locationname', flat=True).distinct()
            shelves_list = Inventory.objects.order_by('shelf').values_list('shelf', flat=True).distinct()
            if not search ==-1:
                inv_list = Inventory.objects.filter(description__icontains=search) | Inventory.objects.filter(modelname__icontains=search) | Inventory.objects.filter(status__icontains=search) | Inventory.objects.filter(category__icontains=search) | Inventory.objects.filter(locationname__icontains=search) | Inventory.objects.filter(serial_number__contains=search) | Inventory.objects.filter(shelf__icontains=search).all()
            elif description == "select menu" and model == "select menu" and status == "select menu" and category == "select menu" and locationname == "select menu" and  shelf == "select":
                inv_list = Inventory.objects.all()
            elif not category =="select menu": 
                if description == "select menu" and model == "select menu" and status == "select menu" and locationname == "select menu" and  shelf == "select":#category only 
                    inv_list = Inventory.objects.filter(category=category).all()
                if not model == "select menu" and status == "select menu" and locationname == "select menu" and  shelf == "select":  #category &  model
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model).all()  
                if not model == "select menu" and not status == "select menu" and locationname == "select menu" and  shelf == "select":  #category & status & model & description
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status).all()  
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and  shelf == "select": #category & status & model & description
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname).all() 
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and not shelf == "select": #category & status & model & description &  cat
                    iinv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname, shelf__contains=shelf).all() 
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and not shelf == "select" and not description  == "select menu" : #category & status & model & description &  cat
                    iinv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname, shelf__contains=shelf, description__icontains=description).all() 
            elif not model =="select menu": 
                if description == "select menu" and status == "select menu" and category == "select menu" and locationname == "select menu" and shelf == "select":#model only 
                    inv_list = Inventory.objects.filter(modelname__contains=model).all()

inventory/templates/Inventory/event.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    {{ index_type }}
{% endblock %}

{% block body %}
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
		<a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">TCLI Inventory Manager</a>
		<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
		<ul class="navbar-nav px-3">
		  <li class="nav-item text-nowrap">
			<a class="nav-link" href="{% url 'inventory:logout' %}"Sign out</a>
		  </li>
		</ul>
    </nav>
	<div class="container-fluid">
	  <div class="row">
		<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
		  <div class="sidebar-sticky pt-3">
			<ul class="nav flex-column">
			    <li class="nav-item">
					<a class="nav-link active" href="{% url 'inventory:index' %}">
					  <span data-feather="home"></span>
					  Search Inventory <span class="sr-only">(current)</span>
					</a>
			    </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'inventory:items' %}">
					  <span data-feather="file"></span>
					  Save/Modify Inventory
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'equipment:index' %}">
					  <span data-feather="file"></span>
					  Save/Modify Equipment
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'locations:index' %}">
					  <span data-feather="users"></span>
					  Save/Modify Site locations
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">
					  <span data-feather="layers"></span>
					  Sign out
					</a>
				 </li>
			 </ul>
		</div>
	</nav>
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			<h2 class="h2">New Ticket | INVENTORY ITEM NUMBER: {{inventory_id}}</h2>
			<div class="btn-toolbar mb-2 mb-md-0">
				<div class="btn-group mr-2">
					<button type="button" id = "share" class="btn btn-sm btn-outline-secondary">Share</button>
					<button type="button" id = "export" class="btn btn-sm btn-outline-secondary">Export</button>
				</div>
			</div>
		</div>
		<form>
			{% csfr_token %}
			<div class="row">
				<div class="col-sm-1 col-lg-6 grid-col">
					<div class="form-group">
						<label>Title: <span class="k-required">(Required)</span></label>
						<input id = "_title" input class="form-control" placeholder="Enter description">
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg-2 grid-col">
					<label>Submitter: <span class="k-required">(Required)</span></label>
					<input type='hidden' name='pfunk' data-select='pfunk'/>
					<select id='_submitter' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'submitter', data-val = "LaPosota,Edward">LaPosota,Edward</option>
						<option data-desc = 'submitter', data-val = "Denizard,John">Denizard,John</option>
						<option data-desc = 'submitter', data-val = "Veron,Oscar">Veron,Oscar</option>
						<option data-desc = 'submitter', data-val = "Ford,Michael">Ford,Michael</option>
					</select>
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					<label>Equipment <span class="k-required"></span></label>
					<input type='hidden' name='_equipment' data-select='_equipment'/>
					<select id='_equipment' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'equipment', data-val = "modem">MODEM</option>
						<option data-desc = 'equipment', data-val = "buc">BUC</option>
						<option data-desc = 'equipment', data-val = "bdc">BDC</option>
						<option data-desc = 'equipment', data-val = "lna">LNA</option>
						<option data-desc = 'equipment', data-val = "lnb">LNB</option>
						<option data-desc = 'equipment', data-val = "amp">AMPLFIER</option>
						<option data-desc = 'equipment', data-val = "ant">ANTENNA</option>
						<option data-desc = 'equipment', data-val = "contr">CONTROLLER</option>
					</select>
				</div>	
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg-2 grid-col">
					<label>Priority: <span class="k-required">(Required)</span></label>
					<input type='hidden' name='pfunk' data-select='pfunk'/>
					<select id='_priority' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'priority', data-val = "high">High</option>
						<option data-desc = 'priority', data-val = "medium">Medium</option>
						<option data-desc = 'priority', data-val = "low">Low</option>
					</select>
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					<label>Owner: <span class="k-required">(Required)</span></label>
					<input type='hidden' name='pfunk' data-select='pfunk'/>
					<select id='_owner' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'owner', data-val = "LaPosota,Edward">LaPosota,Edward</option>
						<option data-desc = 'owner', data-val = "Denizard,John">Denizard,John</option>
						<option data-desc = 'owner', data-val = "Christopher,Michael">Christopher,Michael</option>
						<option data-desc = 'owner', data-val = "Brewer,Megan">Brewer,Megan</option>
					</select>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2 col-lg-2 grid-col">
					<label>Site<span class="k-required"></span></label>
					<input type='hidden' name='site' data-select='site'/>
					<select id='_site' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'location', data-val = "speedcast">Speedcast Hauppauge" </option>
					</select>
				</div>	
				<div class="col-sm-1 col-lg-2 grid-col">
					<label>Shelf <span class="k-required"></span></label>
					<input type='hidden' name='pfunk2' data-select='pfunk2'/>
					<select id='_shelf' class="browser-default custom-select custom-select-lg mb-3" >
						<option selected>select menu</option>
						<option data-desc = 'shelf', data-val = "A1">A1</option>
						<option data-desc = 'shelf', data-val = "A2">A2</option>
						<option data-desc = 'shelf', data-val = "A3">A3</option>
						<option data-desc = 'shelf', data-val = "A4">A4</option>
						<option data-desc = 'shelf', data-val = "A5">A5</option>
						<option data-desc = 'shelf', data-val = "B1">B1</option>
						<option data-desc = 'shelf', data-val = "B2">B2</option>
						<option data-desc = 'shelf', data-val = "B3">B3</option>
						<option data-desc = 'shelf', data-val = "B4">B4</option>
						<option data-desc = 'shelf', data-val = "B5">B5</option>
						<option data-desc = 'shelf', data-val = "C1">C1</option>
						<option data-desc = 'shelf', data-val = "C2">C2</option>
						<option data-desc = 'shelf', data-val = "C3">C3</option>
						<option data-desc = 'shelf', data-val = "C4">C4</option>
						<option data-desc = 'shelf', data-val = "B5">C5</option>
						<option data-desc = 'shelf', data-val = "H1">H1</option>
						<option data-desc = 'shelf', data-val = "H2">H2</option>
						<option data-desc = 'shelf', data-val = "H3">H3</option>
						<option data-desc = 'shelf', data-val = "H4">H4</option>
						<option data-desc = 'shelf', data-val = "H5">H5</option>
						<option data-desc = 'shelf', data-val = "K1">K1</option>
						<option data-desc = 'shelf', data-val = "K2">K2</option>
						<option data-desc = 'shelf', data-val = "K3">K3</option>
						<option data-desc = 'shelf', data-val = "K4">K4</option>
						<option data-desc = 'shelf', data-val = "K5">K5</option>
						<option data-desc = 'shelf', data-val = "L1">L1</option>
						<option data-desc = 'shelf', data-val = "L2">L2</option>
						<option data-desc = 'shelf', data-val = "L3">L3</option>
						<option data-desc = 'shelf', data-val = "L4">L4</option>
						<option data-desc = 'shelf', data-val = "L5">L5</option>
					</select>
				</div>
			</div>
			<div class="row">	
				<div class="col-sm-3 col-lg-6 grid-col">
					<div class="form-group">
						<label>Summary: </label><br>
						<textarea id="txt_comments" name="txt_comments" rows="15" cols="74">
						</textarea>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<button id = "title" data-search="save"  class="btn btn-primary">Save</button>
						</div>
					</div>
				</div>
			</div>	
		</form>
	</main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="{% static 'inventory/css/bootstrap.css' %}"></script>
<script>window.jQuery || document.write('<script src="{% static 'inventory/js/jquery.slim.min.js' %}"><\/script>')</script><script src="{% static 'inventory/js/bootstrap.bundle.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js' %}"></script>
</body>
{% endblock %}

</html>

inventory/templates/Inventory/layout.html
{% load static %}

<!DOCTYPE html>
	<head>
		<meta charset="utf-8">
		<link rel="icon" type="image/x-icon" href="{% static 'inventory/images/rings_16x16.ico' %}">
		<title>TCLI Inventory Management</title>	
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Inventory Management page">
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="{% static 'inventory/css/bootstrap.css' %}">
		<!-- Book Search -->
		<link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/grid/">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
		<link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.default.min.css" rel="stylesheet" />1
		<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
		<script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.all.min.js"></script>
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
		<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
		
		<style>
			.bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
			}

			@media (min-width: 768px) {1112
			.bd-placeholder-img-lg {
			  font-size: 3.5rem;
			}
			}
			.k-required_{
			color:red;
			font-style: italic;
						}
		</style>
		<!-- Custom styles for this template -->
		<link href="{% static 'inventory/css/grid.css' %}" rel="stylesheet">
		<link href="{% static 'inventory/css/styles.css' %}" rel="stylesheet">
    <body>
        <h1>{% block heading %}{% endblock %}</h1>
        {% block body %}
        {% endblock %}
		{% block footer %}
		{% endblock %}
    </body>
</html>