archive/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include("hello.urls")),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    path('inventory/', include("inventory.urls")),
    ]

equipment/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom django.conf import settingsfrom django.conf.urls.static import staticfrom . import viewsfrom django.contrib.auth.decorators import login_required, permission_requiredfrom equipment.views import (    EquipmentView,    ModelView)app_name = "equipment"urlpatterns =[    path('', login_required(EquipmentView.as_view(template_name="index.html")), name='equipment'),    path('model/<slug:model_id>', login_required(views.loadmodel), name='model'),    path('newmodel', login_required(views.newmodel), name='newmodel'),    path('model', login_required(views.savemodel), name='savemodel'),    path('images', login_required(views.showimage), name='showimage'),        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)        

inventory/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom inventory.views import (    InventoryView,    SearchView)app_name = "inventory"urlpatterns =[	path('', login_required(InventoryView.as_view(template_name="index.html")), name='inven'),	url(r'^$', SearchView.as_view(), name='search'),	path("update_inv", views.update_inv, name ="update_inv"),	path("save_event", views.save_event, name ="save_event"),	path("items", views.items, name ="items"),	path("item", views.item, name ="item"),	path("report", views.report, name ="report"),	path("inv_report", views.inv_report, name ="inv_report"),	path("upload_file", views.upload_file, name ="upload_file"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

locations/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom locations.views import (    LocationView)app_name = "locations"urlpatterns =[    path('', login_required(LocationView.as_view(template_name="index.html")), name='location'),    path("site/<slug:location_id>/", views.site, name ="site"),    path("searchsite", views.searchsite, name ="searchsite"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

tcli/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^users/',include('users.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #url(r'^inventory/',include('inventory.urls')),
    #path('/inventory', search_view),
    path('inventory/', include("inventory.urls"),name='inven'),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

inventory/forms.py
#https://www.pluralsight.com/guides/work-with-ajax-django

from .models import Inventory
from django import forms
import datetime

class InventoryForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(InventoryForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Inventory
        fields = ("__all__")
        

inventory/views.py
from django import forms
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.core import serializers
from .forms import InventoryForm
from datetime import date
from django.urls import reverse, reverse_lazy
from equipment.models import Model
from locations.models import Location
from inventory.models import Inventory, Events
from django.views import View
import datetime
from django.contrib.auth.decorators import login_required

# Create your views here.
class InventoryView(View):
    '''
    #~~~~~~~~~~~Load Item database from csv. must put this somewhere else later"
    import csv
    timestamp  = date.today()  
    import csv
    timestamp  = date.today()
    CSV_PATH = 'items.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0
    # Remove all data from Table
    #Inventory.objects.all().delete()
    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)

    for category, shelf, modelname, serial_number, description, locationname,  status, remarks,last_update,update_by in reader:
        Inventory.objects.create(category=category, shelf=shelf, modelname=modelname, serial_number=serial_number, description=description, locationname=locationname, 
         status=status, remarks=remarks, last_update=datetime.datetime.strptime(last_update, '%m/%d/%Y'), update_by=update_by)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ') 
    '''
    '''
    #~~~~~~~~~~~Load Events database from csv. must put this somewhere else later"
    import csv
    timestamp  = date.today()      
    CSV_PATH = 'events.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0

    # Remove all data from Table
    Events.objects.all().delete()

    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)
    for event_type, event_date, operator, comment, inventory_id, locationname, rma, rtv, mr, in reader:
        print('event date=',event_date)
        Events.objects.create(event_type=event_type, event_date=datetime.datetime.strptime(event_date, '%m/%d/%Y'), operator=operator,comment=comment, locationname=locationname, mr=mr, rtv =rtv, rma =rma, inventory_id=inventory_id)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ')
    
    #~~~~~~~~~~~Load Events database from csv. must put this somewhere else later"   
    '''
    '''
    import csv
    timestamp  = date.today()
    CSV_PATH = 'locations.csv'
    print('csv = ',CSV_PATH)

    contSuccess = 0
    # Remove all data from Table
    Location.objects.all().delete()

    f = open(CSV_PATH)
    reader = csv.reader(f)
    print('reader = ',reader)
    for name, address, city, state,zip_code, phone, email, website, lat, lng, created_on ,last_entry in reader:
        if lat=="": lat=40.815320
        if lng=="": lng=-73.237710
        Location.objects.create(name=name, address=address, city=city, state=state, zip_code=zip_code, phone=phone, email=email,
                 website=website,active=True, lat=float(lat), lng=float(lng), created_on=timestamp, last_entry=timestamp)
        contSuccess += 1
    print(f'{str(contSuccess)} inserted successfully! ')
    '''
    #load_iventory_csv(True)
    #load_events_csv(True)
    form_class = InventoryForm
    template_name = "index.html"
    success_url = reverse_lazy('inventory:inv')
    def get(self, *args, **kwargs):
        form = self.form_class()
        try:
            
            description=-1
            category=-1
            model=-1
            status=-1
            locationname=-1
            shelf=-1
            search=-1
            
            print("in GET")
            desc_list = Inventory.objects.order_by('description').values_list('description', flat=True).distinct()
            models_list = Inventory.objects.order_by('modelname').values_list('modelname', flat=True).distinct()
            categorys_list = Inventory.objects.order_by('category').values_list('category', flat=True).distinct()
            status_list = Inventory.objects.order_by('status').values_list('status', flat=True).distinct()
            locations_list = Inventory.objects.order_by('locationname').values_list('locationname', flat=True).distinct()
            shelves_list = Inventory.objects.order_by('shelf').values_list('shelf', flat=True).distinct()
            inv = Inventory.objects.all()
        except IOError as e:
            print ("Lists load Failure ", e)
            print('error = ',e) 
        return render (self.request,"inventory/index.html",{"form": form, "inventory": inv, "desc_list":desc_list, "status_list":status_list,
           "models_list":models_list, "locations_list":locations_list, "shelves_list":shelves_list,"categorys_list":categorys_list, "index_type":"INVENTORY",
           'description':description,'model':model,'status':status, 'category':category, 'locationname':locationname, 'shelf':shelf,'search':search})
    
    def post(self, request, *args, **kwargs):
        try: 
            #print("in POST")
            json_data = []
            inv_list = []
            inv = []
            form = self.form_class()
            #print('request =',request)
            model = request.POST.get('_model', -1)
            #print('model = ',model)
            description = request.POST.get('_desc', -1)
            #print('description = ',description)
            status = request.POST.get('_status', -1)
            #print('status =',status)
            category = request.POST.get('_category', -1)
            #print('category =',category)
            locationname = request.POST.get('_site', -1)
            #print('locationname =',locationname)
            shelf = request.POST.get('_shelf', -1)
            #print('shelf =',shelf)
            select = request.POST.get('sel', -1)
            #print('select =',select)
            search = request.POST.get('search', -1)
            #print('search =',search)
            print_report = request.POST.get('monthly_report', -1)
            #print('print_report =',print_report)
            success = True
            
            

            desc_list = Inventory.objects.order_by('description').values_list('description', flat=True).distinct()
            models_list = Inventory.objects.order_by('modelname').values_list('modelname', flat=True).distinct()
            categorys_list = Inventory.objects.order_by('category').values_list('category', flat=True).distinct()
            status_list = Inventory.objects.order_by('status').values_list('status', flat=True).distinct()
            locations_list = Inventory.objects.order_by('locationname').values_list('locationname', flat=True).distinct()
            shelves_list = Inventory.objects.order_by('shelf').values_list('shelf', flat=True).distinct()
            if not search ==-1:
                inv_list = Inventory.objects.filter(description__icontains=search) | Inventory.objects.filter(modelname__icontains=search) | Inventory.objects.filter(status__icontains=search) | Inventory.objects.filter(category__icontains=search) | Inventory.objects.filter(locationname__icontains=search) | Inventory.objects.filter(serial_number__contains=search) | Inventory.objects.filter(shelf__icontains=search).all()
            elif description == "select menu" and model == "select menu" and status == "select menu" and category == "select menu" and locationname == "select menu" and  shelf == "select":
                inv_list = Inventory.objects.all()
            elif not category =="select menu": 
                if description == "select menu" and model == "select menu" and status == "select menu" and locationname == "select menu" and  shelf == "select":#category only 
                    inv_list = Inventory.objects.filter(category=category).all()
                if not model == "select menu" and status == "select menu" and locationname == "select menu" and  shelf == "select":  #category &  model
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model).all()  
                if not model == "select menu" and not status == "select menu" and locationname == "select menu" and  shelf == "select":  #category & status & model & description
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status).all()  
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and  shelf == "select": #category & status & model & description
                    inv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname).all() 
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and not shelf == "select": #category & status & model & description &  cat
                    iinv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname, shelf__contains=shelf).all() 
                if not model == "select menu" and not status == "select menu" and not locationname == "select menu" and not shelf == "select" and not description  == "select menu" : #category & status & model & description &  cat
                    iinv_list = Inventory.objects.filter(category=category, modelname__contains=model, status__contains=status, locationname__contains=locationname, shelf__contains=shelf, description__icontains=description).all() 
            elif not model =="select menu": 
                if description == "select menu" and status == "select menu" and category == "select menu" and locationname == "select menu" and shelf == "select":#model only 
                    inv_list = Inventory.objects.filter(modelname__contains=model).all()

inventory/templates/inventory/item.html
{% extends "inventory/layout.html" %}
{% load static %}

{% block title %}
    {{ index_type }}
{% endblock %}

{% block body %}
<body >
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
		<a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">TCLI Inventory Manager</a>
		<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
		<ul class="navbar-nav px-3">
		  <li class="nav-item text-nowrap">
		    <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
		  </li>
		</ul>
    </nav>
	<div class="container-fluid">
	  <div class="row">
		<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
		  <div class="sidebar-sticky pt-3">
			<ul class="nav flex-column">
			    <li class="nav-item">
					<a class="nav-link active" href="{% url 'index' %}">
					  <span data-feather="home"></span>
					  Home <span class="sr-only">(current)</span>
					</a>
			    </li>
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'inventory:inven' %}">
					  <span data-feather="home"></span>
					  Search Inventory <span class="sr-only">(current)</span>
					</a>
			    </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'inventory:items' %}">
					  <span data-feather="file"></span>
					  Create Inventory items
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'equipment:equipment' %}">
					  <span data-feather="file"></span>
					  Search Equipment
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'equipment:newmodel' %}">
					  <span data-feather="file"></span>
					  Add Equipment
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'locations:location' %}">
					  <span data-feather="users"></span>
					  Add Site locations
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'inventory:report' %}?inventory_id={{active_inv.id }}">
					  <span data-feather="users"></span>
					  Inventory Events Report
					</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">
					  <span data-feather="layers"></span>
					  Log out
					</a>
				 </li>
			 </ul>
		</div>
	</nav>
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
	    <input type='hidden' id = '_id' value = {{active_inv.id}} name='inventory_id' data-select='inventory_id'/>
		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
			{% if active_inv %}
				<h1 class="h2"> S/N: {{active_inv.serial_number}}      Model: {{active_inv.modelname}}   </h1>
			{% else %}
				<h1 class="h1"> INVENTORY ITEM:</h1>
			{% endif %}
			<form action = {% url 'inventory:save_event' %}  method="post">
			<div class="btn-toolbar mb-2 mb-md-0">
				<div class="btn-group mr-2">
					<button type="submit" id = "update_inv" name = "update_inv" class="btn btn-lg btn-outline-secondary">update</button>
					<button type="submit" id = "del_inv" name = "del_inv" class="btn btn-lg btn-outline-secondary">Delete</button>
				</div>
			</div>
			<form action = {% url 'inventory:save_event' %}  method="post">
		</div>
		<form action = {% url 'inventory:save_event' %}  method="post">
		    {% csrf_token %}
			<div class="row">
				<div class="col-sm-5 col-lg-6 grid-col">
					<div class="form-group">
						<label>Inventory Item</label>
						<p></p>
						<p class = 'row_' id = '_cat'>Category: {{active_inv.category}}</p>
						<p class = 'row_' id = '_status'>Status: {{active_inv.status}}</p>
						<p class = 'row_' id = '_loc'>Location: {{active_inv.locationname}}</p>
						<p class = 'row_' id = '_shelf'>Shelf: {{active_inv.shelf}}</p>
						<p class = 'row_' id = '_desc'>Description: {{active_inv.description}}</p>
						<p class = 'row_' id = '_model'>Model: {{active_inv.modelname}}</p>
						<p class = 'row_' id = '_sn'>Serial Number: {{active_inv.serial_number}}</p>
						<p class = 'row_' id = '_street'>Last Update: {{active_inv.last_update}}</p>
						<a class = 'row_' id = '_street'>By: {{active_inv.update_by}}</a>
					</div>
				</div>
				
				<div class="col-sm-2 col-lg-3 grid-col">
					<div class="thumbnail">
						<img src="{{ uploaded_file_url }}" class="img-responsive" alt="Cinque Terre">
						<div class="caption" >
							<p>Model:{{active_inv.modelname}}</p>
						</div>
					</div>	
				</div>
			</div>	
			<hr class="my-2">
			{% if event == 'n/a' %}
				<h3 id ='_event_change' name ='_event_change'  >Add new Event</h2>
			{% else %}
				<h3 id ='_event_change' name ='_event_change'  >Update or Delete this Event</h2>
			{% endif %}
			<hr class="my-2">			
			<div class="row">	
			    <div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label for="_date">Event Date</label>
						{% if event != 'n/a' %}
							<input value={{event.event_date|date:"Y-m-d"}} id = "_date"  name = "_date"  class="form-control"  required>
						{% else %}
							<input value={{today|date:"Y-m-d"}}  id = "_date"  name = "_date" input class="form-control"   required>
						{% endif %}
					</div>	
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					 <div class="form-group">
						<label>Event Type<span class="k-required"></span></label>
						<input type='hidden' name='event' data-select='event'/>
						<select id='_event' onchange="this.nextElementSibling.value=this.value" name = '_event' class="browser-default custom-select custom-select-lg mb-3"  >
							{% if event != 'n/a' %}
								<option selected>{{event.event_type}}</option>
							{% else %}
								<option value=""></option>
							{% endif %}	
							<option data-desc = 'standard', value = "standard">STD</option>
							<option data-desc = 'RMA', value = "rma">RMA</option>
							<option data-desc = 'MR', value = "mr">MR</option>
							<option data-desc = 'Verified', value = "VERIFIED">VERIFIED</option>
							<option data-desc = 'Returned', value = "RETURNED">RETURNED</option>
							<option data-desc = 'Shipped', value = "SHIPPED">SHIPPED</option>
							<option data-desc = 'Missing', value = "MISSING">MISSING</option>
							<option data-desc = 'Testing', value = "TESTING">TESTING</option>
							<option data-desc = 'Repair', value = "REPAIR">REPAIR</option>
							<option data-desc = 'Update', value = "update">UPDATE</option>
							<option data-desc = 'Remove', value = "remove">REMOVE</option>
							<option data-desc = 'Failure', value = "failure">FAILURE</option>
						</select>
					</div>	
				</div>
			    <div class="col-sm-2 col-lg-2 grid-col">
					<div class="form-group">
						<label>Site: <span class="k-required"></span></label>
						<input type='hidden' name='_loc' id='_loc' data-select='loc'/>
						<select id='_site' name = '_site' class="browser-default custom-select custom-select-lg mb-3" >
							{% if event != 'n/a' %}
								<option selected>{{event.locationname}}</option>
							{% else %}
								<option selected>select location</option>
							{% endif %}
							{% for location in locations_list %}
								<option data-desc = 'location', data-val = "{{location}}">{{location}}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2 col-lg-4 grid-col">
						<div class="form-group">
							<label for="_po">RMA #</label>
							{% if event.rma %}
								<input value="{{event.rma}}" id="_rma"  name="_rma" input class="form-control" >
							{% else %}
								<input id="_rma" name="_rma" input class="form-control" placeholder="Enter RMA">
							{% endif %}
						</div>
					</div>
					<div class="col-sm-2 col-lg-4 grid-col">
						<div class="form-group">
							<label for="_mr">MR #</label>
							{% if event.mr %}
								<input  value = "{{event.mr}}" id ="_mr"  name = "_mr" input class="form-control">
							{% else %}
								<input id ="_mr" name= "_mr" input class="form-control" placeholder="Enter MR">
							{% endif %}
						</div>
					</div>
				</div>	
			</div>
			<div class="row">	
			    <div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label for="_date">Operator</label>
						{% if event != 'n/a' %}
							<input value = "{{event.operator}}" id = "i_operator"  name = "_operator" input class="form-control"  required >
						{% else %}
							<input value ="{{active_operator}}" id = "i_operator"  name = "_operator" input class="form-control" placeholder='Add operator'  required >
						{% endif %}
					</div>	
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group"> 
						<label for="_date">inventory ID</label>
						<input id = "i_id"  name = "i_id" input class="form-control" value="{{active_inv.id}}"} readonly>
					</div>	
				</div>
				<div class="col-sm-1 col-lg-2 grid-col">
					<div class="form-group">
						<label for="_date" id ='el_id'>Event ID</label>
						{% if event != 'n/a' %}
							<input id = "e_id" name = "e_id" input class="form-control" value = {{event.id}} readonly>
						{% else %}
							<input id = "e_id" name = "e_id" input class="form-control" placeholder='Added automatically' readonly>
						{% endif %}
					</div>	
				</div>
			</div>
			<div class="row">
				<div class="col-sm-3 col-lg-4 grid-col">
					<div class="form-group">
						<label>Event Description: </label><br>
						{% if event != 'n/a' %}
							<textarea id="_comments" name = "_comments" rows="3" cols="68" style="align-content:left">{{event.comment}}</textarea>
						{% else %}
							<textarea id="_comments" name = "_comments" rows="3" cols="68" style="text-align:left"/>
						{% endif %}
						
						</textarea>
					</div>
				</div>
				{% if event == 'n/a' %}
					<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<input type="submit" id = "_save" name = "_save" data-save="save"  value="Add new event">
						</div>
					</div>
					<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<input type="submit" id = "_clear" name = "_clear" data-update="clear"  value="Clear">
						</div>
					</div>
				{% else %}
					<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<input type="submit" id = "_update" name = "_update" data-update="save"  value="Update event">
						</div>
					</div>
					<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<input type="submit" id = "_clear" name = "_clear" data-update="clear"  value="Clear">
						</div>
					</div>
					<div class="col-sm-1 col-lg-2 grid-col">
						<div class="form-group">
							<input type="submit" id = "_delete" name = "_delete" data-delete="save"  value="Delete event">
						</div>
					</div>
					
			    {% endif %}
			</div>
		</div>
		<hr class="my-2">
		</form>
		<h2 class="text-center" ID='e_id' value ='e_id' >S/N # {{active_inv.serial_number}} Event List</h2>
		<div class="table-responsive">
			 <table id = "table_id" class="table table-striped table-sm">
				<thead>
					<tr>
					  <th>Event Type</th>
					  <th>Event Date</th>
					  <th>Event Description</th>
					  <th>location</th>
					  <th>Operator</th>
					  <th>RMA</th>
					  <th>MR</th>
					</tr>
				</thead>
				<tbody>
				{% for event in event_list %}
				<tr>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.event_type}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.event_date}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.comment}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.locationname}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.operator}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.rma}}</td>
					<td><a class="nav-link" href="{% url 'inventory:item' %}?inventory_id={{active_inv.id }}&event_id={{event.id}}">{{event.mr}}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'inventory/js/jquery.slim.min.js' %}"><\/script>')</script><script src="{% static 'inventory/js/bootstrap.bundle.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>                           
</body>
{% endblock %}

</html>

inventory/templates/inventory/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link rel="icon" type="image/x-icon" href="{% static 'inventory/images/rings_16X16.ico' %}">
		<title>TCLI Inventory Management</title>	
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Inventory Management page">
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="{% static 'inventory/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'inventory/css/styles.css' %}">
		<!-- Book Search -->
		<link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/grid/">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
		<link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.default.min.css" rel="stylesheet" />
		<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
		<script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.all.min.js"></script>
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
		<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
        
		<!-- Custom styles for this template -->
		<link href="{% static 'inventory/css/grid.css' %}" rel="stylesheet">
		<link href="{% static 'inventory/css/styles.css' %}" rel="stylesheet">
	</head>
	<body>
	   {% block body %}
	   {% endblock %}
	</body>
</html>