archive/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include("hello.urls")),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    path('inventory/', include("inventory.urls")),
    ]

equipment/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom django.conf import settingsfrom django.conf.urls.static import staticfrom . import viewsfrom django.contrib.auth.decorators import login_required, permission_requiredfrom equipment.views import (    EquipmentView,    ModelView)app_name = "equipment"urlpatterns =[    path('', login_required(EquipmentView.as_view(template_name="index.html")), name='equipment'),    path('model/<slug:model_id>', login_required(views.loadmodel), name='model'),    path('newmodel', login_required(views.newmodel), name='newmodel'),    path('model', login_required(views.savemodel), name='savemodel'),    path('images', login_required(views.showimage), name='showimage'),        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)        

inventory/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom inventory.views import (    InventoryView,    SearchView)app_name = "inventory"urlpatterns =[	path('', login_required(InventoryView.as_view(template_name="index.html")), name='inven'),	url(r'^$', SearchView.as_view(), name='search'),	path("update_inv", views.update_inv, name ="update_inv"),	path("save_event", views.save_event, name ="save_event"),	path("items", views.items, name ="items"),	path("item", views.item, name ="item"),	path("report", views.report, name ="report"),	path("inv_report", views.inv_report, name ="inv_report"),	path("upload_file", views.upload_file, name ="upload_file"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

locations/urls.py
from django.urls import pathfrom django.conf.urls import urlfrom . import viewsfrom django.conf import settingsfrom django.conf.urls.static import staticfrom django.contrib.auth.decorators import login_required, permission_requiredfrom locations.views import (    LocationView)app_name = "locations"urlpatterns =[    path('', login_required(LocationView.as_view(template_name="index.html")), name='location'),    path("site/<slug:location_id>/", views.site, name ="site"),    path("searchsite", views.searchsite, name ="searchsite"),    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

tcli/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^users/',include('users.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #url(r'^inventory/',include('inventory.urls')),
    #path('/inventory', search_view),
    path('inventory/', include("inventory.urls"),name='inven'),
    path('locations/', include("locations.urls")),
    path('equipment/', include("equipment.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

templates/users/urls.py
from django.conf.urls import url
from users import views
# SET THE NAMESPACE!
app_name = 'users'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),    
]

users/urls.py
from django.conf.urls import url
from users import views
# SET THE NAMESPACE!
app_name = 'users'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),    
]

templates/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

def __str__(self):
    return self.user.username

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

def __str__(self):
    return self.user.username

templates/users/forms.py
from django import formsfrom users.models import UserProfileInfofrom django.contrib.auth.models import Userclass UserForm(forms.ModelForm):	password = forms.CharField(widget=forms.PasswordInput())	class Meta():		model = User		fields = ('username','password','email')class UserProfileInfoForm(forms.ModelForm):	class Meta():		model = UserProfileInfo		fields = ('portfolio_site','profile_pic')

users/forms.py
from django import formsfrom users.models import UserProfileInfofrom django.contrib.auth.models import Userclass UserForm(forms.ModelForm):	password = forms.CharField(widget=forms.PasswordInput())	class Meta():		model = User		fields = ('username','password','email')class UserProfileInfoForm(forms.ModelForm):	class Meta():		model = UserProfileInfo		fields = ('portfolio_site','profile_pic')

users/templates/users/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="TCLI Inventory Management" content="">
	<link rel="icon" type="image/x-icon" href="{% static 'users/images/rings_16x16.ico' %}">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>TCLI Inventory Management</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/product/">

    <!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="{% static 'users/css/bootstrap.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'users/css/product.css' %}">
  </head>
  <body>
    <nav class="site-header sticky-top py-1">

  <div class="container d-flex flex-column flex-md-row justify-content-between">
    {% if user.is_authenticated %}
		<a class="py-2" href="{% url 'logout' %}" aria-label="logut">
	{% else %}
		<a class="py-2" href="{% url 'users:user_login' %}" aria-label="login">
	{% endif %}
     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </a>
    <a class="py-2 d-none d-md-inline-block" href="{% url 'admin:index' %}">Admin</a>
	<a class="py-2 d-none d-md-inline-block" href="{% url 'users:register' %}">Register</a>
    {% if user.is_authenticated %}
		<a class="py-2 d-none d-md-inline-block" href="{% url 'logout' %}">Logout</a>
		<a class="py-2 d-none d-md-inline-block" href="{% url 'admin:password_change' %}">change password</a>
	{% else %}
		<a class="py-2 d-none d-md-inline-block" href="{% url 'users:user_login' %}">Login</a>
		<a class="py-2 d-none d-md-inline-block" href="#">reset password</a>
	{% endif %}
   </div>
</nav>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <div class = "test">
		<img src="{% static 'users/images/logo.png' %}" class="img-fluid"; "max-width: 100%;" height auto" ;alt="Responsive image">
  </div>
    <h1 class="display-4 font-weight-normal">Inventory Management</h1>
    <div>
		{% block body_block %}
		{% endblock %}
    </div>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  <small class="d-block mb-3 text-muted">&copy; TCLI FTI-SAT Inventory Control © 2020</small>
</div>



<footer class="container py-5">
  <div class="row">
	<div class="col-6 col-md">
	{% if user.is_authenticated %}
		<h5>Inventory</h5>
		<ul class="list-unstyled text-small">
			<li><a class="text-muted" href="{% url 'inventory:inven' %}">Search Inventory</a></li>
			<li><a class="text-muted" href="{% url 'inventory:items' %}">Create new Inventory Item</a></li>
			<li><a class="text-muted" href="{% url 'inventory:items' %}">Event History</a></li>
		</ul>
	{% endif %}
	</div>
    <div class="col-6 col-md">
	{% if user.is_authenticated %}
        <h5>Equipment</h5>
        <ul class="list-unstyled text-small">
			<li><a class="text-muted" href="{% url 'equipment:equipment' %}">Search Models</a></li>
			<li><a class="text-muted" href="{% url 'equipment:newmodel' %}">Create new Model</a></li>
		</ul>
	{% endif %}
    </div>
    <div class="col-6 col-md">
	{% if user.is_authenticated %}
        <h5>Site Locations</h5>
        <ul class="list-unstyled text-small">
	    	<li><a class="text-muted" href="{% url 'locations:location' %}">Search locations</a></li>
			<li><a class="text-muted" href="{% url 'locations:location' %}">Create new Site</a></li>
		</ul>
	{% endif %}
    </div>
   </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src={% static 'users/js/jquery.slim.min.js' %}"><\/script>')</script><script src="{% static 'users/js/bootstrap.bundle.js' %}"></script></body>
</html>

users/templates/users/dashboard.html
<!--users/templates/users/dashboard.html-->{% extends 'base.html' %}{% block content %}Hello, {{ user.username|default:'Guest' }}!<div>    {% if user.is_authenticated %}        <a href="{% url 'logout' %}">Logout</a>        <a href="{% url 'password_change' %}">Change password</a>    {% else %}        <a href="{% url 'login' %}">Login</a>    {% endif %}</div>{% endblock %}

users/templates/users/index.html
{% extends "users/base.html" %}{% block body_block %}<div class="container">  <div class="jumbotron">        {% if user.is_authenticated %}		<h1>TCLI Authorized user</h1>        <h2>Hello {{ user.username }}</h2>    {% else %}		<h1>TCLI Security</h1>        <h2>Please Login</h2>    {% endif %}  </div></div>{% endblock %}

users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="TCLI login ">1
		<link rel="icon" type="image/x-icon" href="{% static 'users/images/rings_16x16.ico' %}">
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'users/css/bootstrap.css' %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
		<link rel="stylesheet" href="{% static 'users/css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'users/css/Footer-Basic.css' %}">
		<link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

		<style>
		  .bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
		  }
		  @media (min-width: 768px) {
			.bd-placeholder-img-lg {
			  font-size: 3.5rem;
			}
		  }
		</style>	
		<link rel="stylesheet" href="{% static 'users/css/signin.css' %}">
	</head>
    <body>
        <h1>{% block heading %}{% endblock %}</h1>
        {% block body %}
        {% endblock %}
		{% block footer %}
		{% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}{% block body_block %}  <div class="container">    <div class="jumbotron">      <h1>Login here :</h1><form method="post" action="{% url 'users:user_login' %}">          {% csrf_token %}          {# A more "HTML" way of creating the login form#}          <label for="username">Username:</label>          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>  </div>{% endblock %}

users/templates/users/login_new.html
{% extends 'users/base.html' %}{% block body_block %}  <div class="container">    <div class="jumbotron">      <h1>Login here :</h1><form method="post" action="{% url 'users:user_login' %}">          {% csrf_token %}          {# A more "HTML" way of creating the login form#}          <label for="username">Username:</label>          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>  </div>{% endblock %}

users/templates/users/login_old.html
{% extends "users/layout.html" %}
{% load static %}

{% block title %}
    {{ index_type }}
{% endblock %}

{% block body %}
<body class="text-center">
	<form action="{% url 'users:user_login' %} class="form-signin"  method="post")>
		{% if message %}
			<diV class="mt-2 mb-3 text-muted">{{ message }}</div>
		{% endif %}
		{% csrf_token %}
		<img src="{% static 'users/images/logo.jpg' %}" class="img-fluid"; "max-width: 100%;" height auto" ;alt="Responsive image">
		<h1 class="h3 mb-3 font-weight-normal">Please login</h1>
		<label for="username" class="sr-only">User Name</label>
		<input type="text" class="form-control" name="username" placeholder={{UserN}}  required autofocus>
		<label for="inputPassword" class="sr-only">Password</label>
		<input type="password" input class="form-control" name="password" placeholder={{PassW}} required autofocus>
		<div class="checkbox mb-3">
			<label>
			  <input type="checkbox" value="remember-me"> Remember me
			</label>
		</div>
		<button class="btn btn-lg btn-primary btn-block" type="submit" value="login">Login</button>
		<p class="mt-2 mb-3 text-muted">&copy; Harris FTI-SAT Inventory Control 2020</p>
	</form>
</body>
{% endblock %}

users/templates/users/password_change_done.html
<!--users/templates/registration/password_change_done.html-->{% extends 'base.html' %}{% block content %}<h2>Password changed</h2><a href="{% url 'dashboard' %}">Back to dashboard</a>{% endblock %}

users/templates/users/password_change_form.html
<!--users/templates/registration/password_change_form.html-->{% extends 'base.html' %}{% block content %}<h2>Change password</h2><form method="post">    {% csrf_token %}    {{ form.as_p }}    <input type="submit" value="Change"></form><a href="{% url 'dashboard' %}">Back to dashboard</a>{% endblock %}

users/templates/users/registration.html
{% extends "users/base.html" %}{% load static %}{% block body_block %}  <div class="container">    <div class="jumbotron">      {% if registered %}        <h1>Thank you for registering!</h1>      {% else %}        <h1>Register Here</h1>        <h3>Just fill out the form.</h3>        <form enctype="multipart/form-data" method="POST">          {% csrf_token %}          {{ user_form.as_p }}          {{ profile_form.as_p }}          <input type="submit" name="" value="Register">        </form>              {% endif %}    </div>  </div>{% endblock %}

users/templates/users/user.html
{% extends "users/base.html" %}
{% load static %}

{% block title %}
    {{ index_type }}
{% endblock %}

{% block body %}
<body class="text-center">
	<img src="{% static 'users/images/logo.png' %}" class="img-fluid"; "max-width: 100%;" height auto" ;alt="Responsive image">
	<h1>Welcome, {{request.user.first_name }}</h1>
	<ul>
		<li>Username: {{request.user.username }}</li>
		<li>Email: {{ request.user.email }}</li>
	</ul>
	<p class="mt-2 mb-3 text-muted">&copy; Harris FTI-SAT Inventory Control 2020</p>
	
</body>
{% endblock %}